### ISSUE TITLE
Get browser compiling

### ISSUE THREAD

**Issue by RangerMauve** [AgregoreWeb/agregore-mobile#8]
Need to figure out how to make the GH actions work.

Do we need to set up a build server? Is the source for that public?

Might be good to figure out how to compile it locally on our machines too (if that's doable)

**Comment by Madrets** [comment]
**Issues when building Chromium:**

1. **ModuleNotFoundError: no module named "dataclasses"**: The dataclasses module comes with python3.7 and above. For older versions, it must be installed with `pip install dataclasses`. However, this error persists even when Python3.9 is installed. To resolve this issue, I copied  `/usr/local/lib/python2.7/dist-packages/dataclasses.py` to `/chromium/ src/tools/android/modularization/convenience` because the dataclasses module was imported in `/chromium/ src/tools/android/modularization/convenience/lookup_dep.py`.
2. **Syntax error in some file**: This error was particularly frustrating because the compiler did a very bad job of reporting its location. The line number given was wrong, and braces in the code appeared as parentheses in the compiler error. Apparently, this is a python bug involving syntax errors when using f-strings. The syntax error is located at `/chromium/src/build/android/gyp/compile_resources.py` on line 835. I changed `...{exit_code=}` to `...{exit_code}`. For more info on the Python bug, see the comment of author Christoph Zwerschke (cito) * at [https://bugs.python.org/issue31140](https://bugs.python.org/issue31140).

**Comment by RangerMauve** [comment]
This is working! We now have some scripts for configuring the chromium and bromite dependencies + running builds.

The builds themselves will only work on Ubuntu 18 machines, so either run them in a docker container or VM or something.

In the meantime we can run the setup scripts to initialize the source tree for chromium so we can add patches.
